### PR TITLE
[WIP] New Trajectories Editor

### PR DESCRIPTION
**Pull request by hadim**
**DO NOT MERGE**
## Introduction

TrackScheme is a nice tool but it has been designed to work with a very specific kind of data if I am not wrong : cell lineages. It makes it hard to modify tracks on others kind of dataset, for example a lot of proteins moving in time.

During my phd (2 years ago now) I have developed a Python widget that take a TrackMate xml file in input and allow the user to modify it with a nice user interface where it can display a 2D plot of all the possible features included in the dataset.

Then he can click on any spots or tracks in the plot in order to edit, remove or add a spot/track. The code is here : https://github.com/hadim/spindle_tracker/tree/master/spindle_tracker/ui but it was very specific to my dataset and only available in Python.

TrajEditor is an alternative to TrackScheme that try to implement all the features of the widget I have developed in Python.

TrajEditor is build with JavaFX and the plots are using JavaFX Chart ; http://docs.oracle.com/javafx/2/charts/jfxpub-charts.htm. (if you know a plotting JavaFX library please tell me).
## TODO
- [x] Plot any feature of a TrackMate `Model`
- [x] Save model as xml file.
- [ ] Plot spots tracks : Each spots in the same track get the same color. 
- [ ] Enable the time slider : plot will update according to the frame selected with the slider 
- [ ] Enable/Disable tracks : the left panel will display a list of the tracks, the suer should be able to enable or disable them in the plot.
- [ ] Color the spots according to a specific feature (not only time tracks)
- [ ] Add multi charts feature : user can add or remove any numbers of charts, all connected together.
- [ ]  Remove spots
- [ ]  Edit spots features
- [ ]  Remove tracks
- [ ]  Edit tracks features
- [ ] Merge tracks
- [ ] Split tracks
- [x] Zoom on the plot 
- [x] Pan on the plot 
- [x] Reset the plot view  
- [x] Zoom only horizontally or vertically with the mouse : see http://www.pyqtgraph.org/documentation/mouse_interaction.html  
- [x] Export plot to image
- [ ] Better plot style
- [ ] Select one or more spots
- [ ] Select one or more tracks
## Bugs
- [ ] `TrajEditor` button in the wizard cannot be launched because of a weird black magic between Swing and JavaFX...
- [ ] Probably related to the above bug : at the initialization I need to find a way so the JavaFX controller `RootLayoutController` can initialize correctly because sometime it causes null pointer exception when trying to interact on the ui before the init is done. While it seems pretty easy to do it for a pure JavaFX application, I don't how to do it with the JavaFX widget in a Swing application.
## How to test/help
- Get the code of this pull request
- Open in Netbeans or Eclipse
- Run the file `src/test/java/fiji/plugin/trackmate/interactivetests/TrajEditorTest.java`

And small animation to show you how it's working at the moment.

t

### CODE REVIEW

**Comment by ctrueden** [comment]
Wow!

Just wondering @hadim, but have you been following the development of https://github.com/fiji/TrackMate3 ?

**Comment by hadim** [comment]
Well I have seen it a while ago but it seems to be a very alpha stage project at the moment and I would like to have this working as quickly as I can. 

That being said I see two options :

- Trackmate3 is mature enough to be used and I switch to it now. 

- If it's not the case I keep going with this PR and port it to Trackmate 3 once it's mature enough. 

What are going to be the big difference btw TM2 and TM3?

**Comment by tinevez** [comment]
:+1:

**Comment by tinevez** [comment]
Hi @hadim 
Do you plan to make it a TrackMate module or an independent plugin?

**Comment by hadim** [comment]
I would like to make it an integrated Trackmate module so the potential userbase is bigger. 

What do you think?

**Comment by tinevez** [comment]
I think that you are the boss.

**Comment by hadim** [comment]
Now I am pretty happy with he plotting library I have.

Now come the hard part : designing a good set of classes to automatically bind in both direction `Spots` and `Tracks` with the `Chart`. So whenever the Trackmate `Model` is updated the changes are propagated to the `Chart`.

Once this is done and if it's correctly done, the last part (editing `Spots` and `Tracks` on the `Chart`) should be easy.

**Comment by ctrueden** [comment]
For binding events, you could design some event classes for use with the
SciJava EventService.

**Comment by hadim** [comment]
Any code example available?

**Comment by hadim** [comment]
Here is what kind of UI I have in mind : 

image4141

(note that it's absolutely not functional at the moment)

Common sense would make me use SciJava EventService but I found some classes in TrackMate that do the same job without using Scijava.

Being really not very confortable enough with Java events magic, I'll probably go for the custom homemade TrackMate solution already here.

The question is : is the TrackMate event system complex enough to achieve this ?

In the future (or for TM3) I'll switch to a Scijava based event system.

Having said that it's not fixed in the stone for now.

**Comment by hadim** [comment]
Note to me : maybe try to use `AbstractTrackMateModelView` ?

**Comment by hadim** [comment]
- [ x] `Model` to `SpotsTableView` binding with the TrackMate event system (very clean and nice system by the way @tinevez).

Next is : 

- [ ] Integrate the `SelectionModel` into the binding.
- [ ] Do binding for `TracksTableView` and `DetailedView`
- [ ] Allow editing from `DetailedView` (bidirectional binding)

- [ ] Transpose the event system to the `Chart`
- [ ] Allow editing from the `Chart`

**Comment by hadim** [comment]
@tinevez did you have time to have a look?

**Comment by hadim** [comment]
Hey guys a small teaser about this PR : 

out-1

I have designed a "bridge" between the Trackmate `Model` and my different views (various table views and plots). The code is bit a mess now and I have some difficulties organising the code (good separation between views and logic).

The biggest feature so far is the `DetailView` that can be edited and the Trackmate `Model` get updated automatically.

In the future I also would like to integrate the images into the window and synchronize all the views (tableview, plots and images with ROIs) together so when the user click/edit/remove/add a spot all the views are updated at the same time.

I think I am not so far to have the correct code design but if someone could have a look and give me some hints that would be really awesome.

Now I understand you're all busy guys so no worry and just give it a try when you have some free time.

**Comment by tinevez** [comment]
Hi @hadim 
Are you still working on this PR?

**Comment by hadim** [comment]
I would like too. I don't know if it's gonna be here or elsewhere (TM3 ?) but the community (and me also) needs an alternative as the lineage viewer for easy trajectories editing.

An interface with a 2D plot where you can easily modify X and Y labels according to spots/trajectories features is really good (I have used it during my PhD, UI was coded in Python).

**Comment by hadim** [comment]
I guess I can close here. I'll keep the branch on my repo if I decide to work on it in the future.

**Pull request closed without merging**
