### PR TITLE
Basic implementation of find maxima detector

### PR DESCRIPTION
**Pull request by thorstenwagner**
Hi, this pull contains the basic implementation of the find maxima detector. It should work with 1D,2D and 3D data but is only tested with 2d data (please find below the test data set).
Strangely, in comparision with the find maxima implementation of ImageJ it give different results for low tolerance values (<10) but quite the same results for higher tolerance values (>20).

Test dataset: https://dl.dropboxusercontent.com/u/560426/100nm_noscale_mean_First10Frames.tif

### CODE REVIEW

**Comment by ctrueden** [comment]
@tinevez Any comments? Or should I merge it?

**Comment by tinevez** [comment]
Please not yet.
We still have work to do on this. Plus I would like to make it an independant TrackMate module rather than have it in the core.

**Comment by ctrueden** [comment]
Sounds good, thanks for the update!

**Comment by tinevez** [comment]
@thorstenwagner I will reject this PR, though it is sound and useful.
No worries, here is why: 

I would favor adding your new detector as an independent module of TrackMate. That way, you would have to refactor your project so that it *depends* on TrackMate, and incorporate the SciJava discovery mechanisms so that TrackMate can detect it as runtime. 

The TrackMate module development is documented here:
http://fiji.sc/How_to_write_your_own_edge_feature_analyzer_algorithm_for_TrackMate
(and goes for 5 pages).

An example of such modules are here:
https://github.com/tinevez/TrackMate-extras
and here
https://github.com/fiji/TrackMate-examples

**Comment by thorstenwagner** [comment]
I will refactor my detector as module as soon as possible.

Best,
Thorsten

Am 21.09.2015 13:52 schrieb Jean-Yves Tinevez: 

> @thorstenwagner [1] I will reject this PR, though it is sound and useful.
> No worries, here is why: 
> 
> I would favor adding your new detector as an independent module of TrackMate. That way, you would have to refactor your project so that it _depends_ on TrackMate, and incorporate the SciJava discovery mechanisms so that TrackMate can detect it as runtime. 
> 
> The TrackMate module development is documented here:
> http://fiji.sc/How_to_write_your_own_edge_feature_analyzer_algorithm_for_TrackMate [2]
> (and goes for 5 pages). 
> 
> An example of such modules are here:
> https://github.com/tinevez/TrackMate-extras [3]
> and here
> https://github.com/fiji/TrackMate-examples [4] 
> 
> --
> Reply to this email directly or view it on GitHub [5].
 

Links:
------
[1] https://github.com/thorstenwagner
[2]
http://fiji.sc/How_to_write_your_own_edge_feature_analyzer_algorithm_for_TrackMate
[3] https://github.com/tinevez/TrackMate-extras
[4] https://github.com/fiji/TrackMate-examples
[5] https://github.com/fiji/TrackMate/pull/57#issuecomment-141950712

**Comment by tinevez** [comment]
@thorstenwagner Tell me how I can help.

**Comment by thorstenwagner** [comment]
@tinevez Invent a machine to make days longer or kids less time consuming ;-)

**Comment by tinevez** [comment]
If I knew how to do that, I would be first to benefit from it ;)

**Comment by tinevez** [comment]
Closing this, waiting on @thorstenwagner for his TrackMate modules.

**Pull request closed without merging**
